### ISSUE TITLE
bayes factor analysis

### ISSUE THREAD

**Issue by hawkrobe** [StanfordPsych254/replication_project#2]
similar to the one done by [Etz & Vandekerckhove (2016)](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0149794) with a figure like this:

<img width="569" alt="bf_figure" src="https://cloud.githubusercontent.com/assets/5262024/16530635/f2e66d82-3f7d-11e6-952b-b588fb82f435.png">

**Comment by hawkrobe** [comment]
This is pretty dire... According to the bayes factor analysis, there are only two projects where our replication provides even _weak_ evidence for the author's alternative hypothesis (the others actually provide weak evidence for the null). Note that this _isn't_ plotted on a log-log plot because it would cut off all but the 2 points where both BFs provide positive evidence.

![image](https://cloud.githubusercontent.com/assets/5262024/16537512/eafa1b06-3fb8-11e6-9c33-48b657618e06.png)

**Comment by mcfrank** [comment]
wow... huh. That does look dire. how sure are you about this? some of those
studies had a lot of participants, and some pretty big t values I thought?

a good way to debug would be to use geom_label_repel from the ggrepel
package to label?

best,

Mike

**Comment by hawkrobe** [comment]
Ah, good tip on the debugging. Turns out I plotted logged values, but then ggplot automatically took the log again when doing the axes :/ here's a fixed version of the fig. It still makes our replications look pretty weak, but at least interpretable. A couple observations:

1) Carolyn's is missing, because we haven't updated the spreadsheet with the relevant test (i.e. for the interaction)
2) One of the originals had such an astronomical BF that it's off the charts (like, >10^25)
3) We should still double-check some of the values we put in the `project_info` frames, as they do seem on the low side... 

![image](https://cloud.githubusercontent.com/assets/5262024/16575816/e9d88742-423f-11e6-8dda-4409db9f9871.png)

**Comment by mcfrank** [comment]
OK, good!

1) I'll fix Carolyn's on or before Friday. The trouble is we may need do
swap to a by-subject effect rather than by-face because they didn't report
the by-face F score. (just p < .001).

2) can always plot that at the limit of the axis label (that's justin
salloum's, I think).

3) yes, agreed.

also, might be nice to add a trend line and a light diagonal for
interpretation, and to use alpha = .5 or something so Juan Arias's doesn't
cover up others.
Mike

**Comment by hawkrobe** [comment]
Great suggestions! I’ll shoot for Friday, too.
