### ISSUE TITLE
smraposo-original.png missing

### ISSUE THREAD

**Issue by hawkrobe** [StanfordPsych254/replication_project#7]
When you try to knit the paper, you get an error: "unable to open ../figures/smraposo-original.png"

It looks like it's missing from the figures directory

**Comment by mcfrank** [comment]
closed.

Mike

**Comment by hawkrobe** [comment]
Hmmm, I still don't see it when I pull -- maybe try pushing again in case it didn't go through?

**Comment by hawkrobe** [comment]
Oh shoot, it actually looks like it's called `sraposo-original.png` in the folder, but `smraposo-original.png` in the project keys. I'll change the name of the figure to match the project key.
